# Generated by Django 2.2.1 on 2019-07-05 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crop_info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('farmer', models.CharField(max_length=20)),
                ('crop_name', models.CharField(max_length=20)),
                ('crop_species', models.CharField(max_length=20)),
                ('geolocation_lat', models.DecimalField(decimal_places=8, max_digits=10)),
                ('geolocation_lon', models.DecimalField(decimal_places=8, max_digits=10)),
                ('crop_age', models.IntegerField()),
                ('crop_height', models.IntegerField()),
            ],
        ),
    ]
