# Generated by Django 2.2.1 on 2019-08-07 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Blockchain', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='crop_info',
            name='geolocation_lat',
        ),
        migrations.RemoveField(
            model_name='crop_info',
            name='geolocation_lon',
        ),
    ]
