# Generated by Django 2.2.1 on 2019-08-12 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blockchain', '0002_auto_20190807_1231'),
    ]

    operations = [
        migrations.CreateModel(
            name='Btn_display',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
